/**
 * X402 payment challenge / verification for builder reads.
 *
 * The personal server speaks an x402-style payment dance to builders on
 * GET /v1/data/:scope. When a request arrives without (or with an invalid)
 * X-PAYMENT header the server issues a 402 challenge: a server-signed
 * RECORD_DATA_ACCESS attestation plus the canonical GenericPayment message
 * the builder must EIP-712 sign. The builder retries with the signed
 * message in X-PAYMENT; the server validates locally, then forwards to
 * `POST /v1/escrow/pay` on the gateway. On 2xx the read proceeds; on
 * 4xx/5xx the server responds with a fresh challenge.
 *
 * This module is wire-format only — it doesn't talk to the gateway or the
 * storage layer. Callers in `api/index.ts` glue it to `gateway.getGrant`
 * (for fee discovery), `IndexEntry.dataPointId/version` (for accessRecord
 * binding), and a direct `fetch` to the gateway for payment forwarding.
 */

import {
  GENERIC_PAYMENT_TYPES,
  RECORD_DATA_ACCESS_TYPES,
  dataRegistryDomain,
  escrowPaymentDomain,
  type DataPortabilityGatewayConfig,
  type GatewayGrantResponse,
} from "@opendatalabs/vana-sdk/browser";
import { recoverTypedDataAddress, type TypedDataDomain } from "viem";
import type { ServerSigner } from "../signing/index.js";

// Per-event recordId on the access attestation. 32 cryptographically random
// bytes — collision-resistant under the DataRegistryV2 `_usedRecordIds`
// set the contract pins per access event.
export function generateRecordId(): `0x${string}` {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return ("0x" +
    Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join(
      "",
    )) as `0x${string}`;
}

// Build a fresh paymentNonce: high 32 bits = Date.now() (ms-monotonic), low
// 32 bits = cryptographic randomness (within-ms collision avoidance). Yields
// a strictly-increasing uint256 across ms ticks while keeping per-ms
// collision probability negligible. Serialized as a decimal string on the
// wire so the gateway's `^[1-9]\d*$` regex accepts it.
//
// Caveat: server-clock regressions can break monotonicity; the gateway
// rejects out-of-order nonces with 409 and the builder retries.
export function nextPaymentNonce(): bigint {
  const rand = new Uint32Array(1);
  crypto.getRandomValues(rand);
  return (BigInt(Date.now()) << 32n) + BigInt(rand[0]);
}

// Recover the millisecond timestamp encoded in the high 32 bits of a nonce
// generated by `nextPaymentNonce`. Used for the optional freshness check
// during X-PAYMENT validation.
export function paymentNonceIssueTimeMs(nonce: bigint): bigint {
  return nonce >> 32n;
}

/**
 * AccessRecord fields the personal server emits in the 402 challenge AND
 * the builder echoes back in X-PAYMENT. Mirrors the gateway's wire shape
 * exactly so the relay can pass it through unchanged.
 */
export interface X402AccessRecord {
  // bytes32 — keccak256(abi.encode(ownerAddress, scope)) per the gateway.
  // Sourced from IndexEntry.dataPointId, populated by the upload worker
  // after gateway.registerDataPoint.
  dataPointId: `0x${string}`;
  // Decimal uint256 string. Matches the IndexEntry.version this read serves.
  version: string;
  // The authenticated builder address (== payerAddress in this flow).
  accessor: `0x${string}`;
  // 32 random bytes minted at challenge time.
  recordId: `0x${string}`;
  // Server-signed EIP-712 over RECORD_DATA_ACCESS_TYPES.
  signature: `0x${string}`;
}

/**
 * GenericPaymentMessage as it appears in the X402 challenge / payload.
 * uint256 fields are decimal strings on the wire.
 */
export interface X402PaymentMessage {
  payerAddress: `0x${string}`;
  opType: string;
  // Lowercased — the gateway normalizes opId via toLowerCase() before
  // EIP-712 recovery, so the builder must sign over the lowercased form.
  opId: `0x${string}`;
  asset: `0x${string}`;
  amount: string;
  paymentNonce: string;
}

/**
 * One option in the 402 response's `accepts` array.
 */
export interface X402Accept {
  // Discriminator for client logic. Currently the only scheme we issue.
  scheme: "vana-escrow-grant";
  network: string;
  asset: `0x${string}`;
  amount: string;
  domain: TypedDataDomain;
  // Echoed for clients that don't want to recompute from the canary SDK.
  types: typeof GENERIC_PAYMENT_TYPES;
  message: X402PaymentMessage;
  // Annotation only — the canonical amount lives on `message.amount`. Lets
  // builders display "you're paying for: registration + access" UX without
  // re-deriving the breakdown.
  breakdown: {
    registrationFee: string;
    dataAccessFee: string;
    // true when this challenge requires paying the registration fee
    // (grant.paymentStatus === "pending"). When false, only dataAccessFee
    // is in `amount`.
    registrationOwed: boolean;
  };
  // Present when the entry has a registered dataPointId. Omitted on
  // first-ingest reads before the sync worker has run.
  accessRecord?: X402AccessRecord;
  // Unix seconds. Stateless: the server doesn't track issued challenges;
  // the builder is responsible for retrying within this window.
  expiresAt: number;
}

/**
 * Body of the 402 Payment Required response.
 */
export interface X402Challenge {
  x402Version: 1;
  error: "PAYMENT_REQUIRED";
  accepts: [X402Accept];
}

/**
 * Body of the X-PAYMENT header (after base64-decoding).
 */
export interface X402Payment {
  x402Version: 1;
  scheme: "vana-escrow-grant";
  network: string;
  payload: {
    message: X402PaymentMessage;
    signature: `0x${string}`;
    accessRecord?: X402AccessRecord;
  };
}

/**
 * Result of validating a parsed X-PAYMENT against the live grant/entry state.
 * On `ok: true`, the caller forwards to the gateway. On `ok: false` it
 * builds a fresh challenge.
 */
export type X402VerifyResult =
  | { ok: true; payment: X402Payment }
  | { ok: false; reason: string };

const CHALLENGE_TTL_SECONDS = 300; // 5 min — challenges are stateless; this
// is purely advisory for clients.
const NONCE_FRESHNESS_MS = 600_000; // accept paymentNonces issued within
// the last 10 minutes (or up to 1 min in the future — clock skew tolerance).
const NONCE_FUTURE_SKEW_MS = 60_000;

const BYTES32_REGEX = /^0x[0-9a-fA-F]{64}$/;
const ADDRESS_REGEX = /^0x[0-9a-fA-F]{40}$/;
const SIGNATURE_REGEX = /^0x[0-9a-fA-F]{130}$/;
const POSITIVE_DECIMAL_INT_REGEX = /^[1-9]\d*$/;
const NON_NEGATIVE_DECIMAL_INT_REGEX = /^(0|[1-9]\d*)$/;

export interface BuildChallengeInput {
  // Recovered Web3Signed signer for the GET — the builder.
  builder: `0x${string}`;
  // The opId that the gateway is about to use for the EIP-712 recovery —
  // already lowercased by the caller.
  grantId: `0x${string}`;
  // Live grant (sourced from gateway.getGrant). Provides fee + paymentStatus.
  grant: GatewayGrantResponse;
  // Network identifier echoed in the challenge. Convention: chain name from
  // the gateway config (e.g. "vana-moksha"). Informational only.
  network: string;
  // Required to compute `escrowPaymentDomain(config).verifyingContract`.
  gatewayConfig: DataPortabilityGatewayConfig;
  // Required to sign the accessRecord. When omitted (or when entry is null
  // or entry.dataPointId is null), the challenge omits accessRecord and the
  // gateway accepts the resulting payment without an on-chain recordDataAccess.
  serverSigner?: Pick<ServerSigner, "signRecordDataAccess">;
  // The owner address signed into the RecordDataAccess message — equals
  // `serverOwner` for personal-server reads.
  serverOwner?: `0x${string}`;
  // The data point + version this read will serve. Required to bind the
  // accessRecord to a specific scope/version. When null the accessRecord
  // is omitted (registration-fee-only payments still work).
  entry?: {
    dataPointId: `0x${string}` | null;
    scope: string;
    version: number;
  };
  // Optional test seam — defaults to ms-monotonic + random uint256.
  generateNonce?: () => bigint;
  // Optional test seam.
  generateRecordIdFn?: () => `0x${string}`;
  // Optional test seam — defaults to Date.now / 1000 + CHALLENGE_TTL_SECONDS.
  now?: () => Date;
}

export async function buildChallenge(
  input: BuildChallengeInput,
): Promise<X402Challenge> {
  const now = input.now?.() ?? new Date();
  const expiresAt = Math.floor(now.getTime() / 1000) + CHALLENGE_TTL_SECONDS;
  const generateNonce = input.generateNonce ?? nextPaymentNonce;
  const generateRecord = input.generateRecordIdFn ?? generateRecordId;

  // The canary `totalDue` already accounts for paymentStatus (registration
  // is omitted when grant.paymentStatus === 'paid'). SDK comment: "snapshot
  // — clients shouldn't cache across requests", so the caller re-fetches.
  const amount = input.grant.fee.totalDue;
  const registrationOwed = input.grant.paymentStatus !== "paid";
  const asset = input.grant.fee.asset as `0x${string}`;

  let accessRecord: X402AccessRecord | undefined;
  if (
    input.serverSigner &&
    input.serverOwner &&
    input.entry &&
    input.entry.dataPointId !== null
  ) {
    const recordId = generateRecord();
    const version = BigInt(input.entry.version);
    const signature = await input.serverSigner.signRecordDataAccess({
      ownerAddress: input.serverOwner,
      scope: input.entry.scope,
      version,
      accessor: input.builder,
      recordId,
    });
    accessRecord = {
      dataPointId: input.entry.dataPointId,
      version: version.toString(),
      accessor: input.builder,
      recordId,
      signature,
    };
  }

  const message: X402PaymentMessage = {
    payerAddress: input.builder,
    opType: "grant",
    opId: input.grantId,
    asset,
    amount,
    paymentNonce: generateNonce().toString(),
  };

  return {
    x402Version: 1,
    error: "PAYMENT_REQUIRED",
    accepts: [
      {
        scheme: "vana-escrow-grant",
        network: input.network,
        asset,
        amount,
        domain: escrowPaymentDomain(input.gatewayConfig),
        types: GENERIC_PAYMENT_TYPES,
        message,
        breakdown: {
          registrationFee: registrationOwed
            ? input.grant.fee.registrationFee
            : "0",
          dataAccessFee: input.grant.fee.dataAccessFee,
          registrationOwed,
        },
        ...(accessRecord ? { accessRecord } : {}),
        expiresAt,
      },
    ],
  };
}

// Decode base64 to UTF-8. Tolerates standard + url-safe alphabets so clients
// can use either. Uses the universally-available `atob` + Web text codecs
// rather than Node's Buffer so this module remains browser-safe (consumed
// by ps-lite as well as the Node server).
function base64decode(input: string): string {
  let s = input.replace(/-/g, "+").replace(/_/g, "/");
  const pad = (4 - (s.length % 4)) % 4;
  s += "=".repeat(pad);
  const binString = atob(s);
  const bytes = Uint8Array.from(binString, (c) => c.codePointAt(0) ?? 0);
  return new TextDecoder().decode(bytes);
}

function base64encode(input: string): string {
  const bytes = new TextEncoder().encode(input);
  let binString = "";
  for (const b of bytes) binString += String.fromCodePoint(b);
  return btoa(binString);
}

/**
 * Parse the X-PAYMENT header value. Returns `null` if missing/malformed —
 * the caller should treat that as "no payment provided" and issue a 402.
 */
export function parsePaymentHeader(
  headerValue: string | null | undefined,
): X402Payment | null {
  if (!headerValue) return null;
  let decoded: string;
  try {
    decoded = base64decode(headerValue.trim());
  } catch {
    return null;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(decoded);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object") return null;
  const obj = parsed as Record<string, unknown>;
  if (obj["x402Version"] !== 1) return null;
  if (obj["scheme"] !== "vana-escrow-grant") return null;
  if (typeof obj["network"] !== "string") return null;
  const payload = obj["payload"];
  if (!payload || typeof payload !== "object") return null;
  const p = payload as Record<string, unknown>;
  const message = p["message"];
  if (!message || typeof message !== "object") return null;
  const m = message as Record<string, unknown>;
  if (
    typeof m["payerAddress"] !== "string" ||
    !ADDRESS_REGEX.test(m["payerAddress"]) ||
    typeof m["opType"] !== "string" ||
    typeof m["opId"] !== "string" ||
    !BYTES32_REGEX.test(m["opId"]) ||
    typeof m["asset"] !== "string" ||
    !ADDRESS_REGEX.test(m["asset"]) ||
    typeof m["amount"] !== "string" ||
    !NON_NEGATIVE_DECIMAL_INT_REGEX.test(m["amount"]) ||
    typeof m["paymentNonce"] !== "string" ||
    !POSITIVE_DECIMAL_INT_REGEX.test(m["paymentNonce"])
  ) {
    return null;
  }
  if (
    typeof p["signature"] !== "string" ||
    !SIGNATURE_REGEX.test(p["signature"])
  ) {
    return null;
  }
  const accessRecordRaw = p["accessRecord"];
  let accessRecord: X402AccessRecord | undefined;
  if (accessRecordRaw !== undefined) {
    if (!accessRecordRaw || typeof accessRecordRaw !== "object") return null;
    const ar = accessRecordRaw as Record<string, unknown>;
    if (
      typeof ar["dataPointId"] !== "string" ||
      !BYTES32_REGEX.test(ar["dataPointId"]) ||
      typeof ar["version"] !== "string" ||
      !POSITIVE_DECIMAL_INT_REGEX.test(ar["version"]) ||
      typeof ar["accessor"] !== "string" ||
      !ADDRESS_REGEX.test(ar["accessor"]) ||
      typeof ar["recordId"] !== "string" ||
      !BYTES32_REGEX.test(ar["recordId"]) ||
      typeof ar["signature"] !== "string" ||
      !SIGNATURE_REGEX.test(ar["signature"])
    ) {
      return null;
    }
    accessRecord = {
      dataPointId: ar["dataPointId"] as `0x${string}`,
      version: ar["version"],
      accessor: ar["accessor"] as `0x${string}`,
      recordId: ar["recordId"] as `0x${string}`,
      signature: ar["signature"] as `0x${string}`,
    };
  }
  return {
    x402Version: 1,
    scheme: "vana-escrow-grant",
    network: obj["network"],
    payload: {
      message: {
        payerAddress: m["payerAddress"] as `0x${string}`,
        opType: m["opType"],
        opId: m["opId"] as `0x${string}`,
        asset: m["asset"] as `0x${string}`,
        amount: m["amount"],
        paymentNonce: m["paymentNonce"],
      },
      signature: p["signature"] as `0x${string}`,
      ...(accessRecord ? { accessRecord } : {}),
    },
  };
}

/**
 * Encode an X402Payment back to a base64 header value. Useful for client
 * code (the personal server only decodes here; this is exported for tests
 * and downstream builders that want a shared serializer).
 */
export function encodePaymentHeader(payment: X402Payment): string {
  return base64encode(JSON.stringify(payment));
}

export interface VerifyPaymentInput {
  // Authenticated Web3Signed signer of the GET. Must equal payment payerAddress
  // and (when accessRecord present) accessRecord.accessor.
  builder: `0x${string}`;
  // Lowercased opId from the GET's Web3Signed payload. Must equal payment.opId.
  grantId: `0x${string}`;
  // Live grant fetched per request for fresh amount/asset checks.
  grant: GatewayGrantResponse;
  // Live index entry being served. The accessRecord (if present) must bind
  // to this entry's dataPointId + version.
  entry?: {
    dataPointId: `0x${string}` | null;
    scope: string;
    version: number;
  };
  // Server's own address — the accessRecord signature must recover to this.
  serverAddress: `0x${string}`;
  // Required for EIP-712 domain construction during signature recovery.
  gatewayConfig: DataPortabilityGatewayConfig;
  // The server's claim about who the data owner is — should equal what was
  // signed into RECORD_DATA_ACCESS_TYPES.ownerAddress when the server emitted
  // the challenge.
  serverOwner?: `0x${string}`;
  payment: X402Payment;
  // Optional test seam — defaults to Date.now()
  nowMs?: () => number;
}

/**
 * Validate a parsed X-PAYMENT against the live grant + entry state. On
 * success the caller forwards the payment verbatim to the gateway. Any
 * failure should result in a fresh 402 challenge.
 *
 * Replay defense is layered: gateway enforces per-(payer, opType, nonce)
 * uniqueness via DB constraint and per-recordId uniqueness via the on-chain
 * `_usedRecordIds` set. Local checks here catch obvious malformed echoes
 * before they reach the gateway.
 */
export async function verifyPayment(
  input: VerifyPaymentInput,
): Promise<X402VerifyResult> {
  const { payment, grant, builder } = input;
  const msg = payment.payload.message;

  // Builder identity: the payment must claim the authenticated signer.
  // Recovery below cryptographically pins this.
  if (msg.payerAddress.toLowerCase() !== builder.toLowerCase()) {
    return {
      ok: false,
      reason: "payerAddress does not match authenticated builder",
    };
  }

  if (msg.opType !== "grant") {
    return { ok: false, reason: `Unsupported opType: ${msg.opType}` };
  }

  if (msg.opId.toLowerCase() !== input.grantId.toLowerCase()) {
    return { ok: false, reason: "opId does not match the request's grantId" };
  }

  // Amount + asset must match the gateway's canonical values. Re-fetched
  // per request, so a builder echoing stale amounts gets rejected here
  // before we hit the gateway.
  if (msg.asset.toLowerCase() !== grant.fee.asset.toLowerCase()) {
    return { ok: false, reason: "asset does not match grant fee asset" };
  }
  if (msg.amount !== grant.fee.totalDue) {
    return {
      ok: false,
      reason: `amount ${msg.amount} != grant.fee.totalDue ${grant.fee.totalDue}`,
    };
  }

  // Stateless freshness check: extract the issue-time from the high 32 bits
  // of paymentNonce and require it within the last ~10 minutes. Cheap; no
  // server state. Catches replays of captured X-PAYMENTs far in the past.
  let nonceBig: bigint;
  try {
    nonceBig = BigInt(msg.paymentNonce);
  } catch {
    return { ok: false, reason: "paymentNonce is not a valid uint256" };
  }
  const issueMs = paymentNonceIssueTimeMs(nonceBig);
  const nowMs = BigInt(input.nowMs?.() ?? Date.now());
  if (issueMs > nowMs + BigInt(NONCE_FUTURE_SKEW_MS)) {
    return { ok: false, reason: "paymentNonce timestamp is in the future" };
  }
  if (nowMs - issueMs > BigInt(NONCE_FRESHNESS_MS)) {
    return {
      ok: false,
      reason: "paymentNonce is older than the freshness window",
    };
  }

  // GenericPayment signature recovery — must recover to the builder.
  let recoveredPayer: `0x${string}`;
  try {
    recoveredPayer = await recoverTypedDataAddress({
      domain: escrowPaymentDomain(input.gatewayConfig),
      types: GENERIC_PAYMENT_TYPES,
      primaryType: "GenericPayment",
      message: {
        payerAddress: msg.payerAddress,
        opType: msg.opType,
        opId: msg.opId,
        asset: msg.asset,
        amount: BigInt(msg.amount),
        paymentNonce: nonceBig,
      },
      signature: payment.payload.signature,
    });
  } catch {
    return { ok: false, reason: "GenericPayment signature recovery failed" };
  }
  if (recoveredPayer.toLowerCase() !== builder.toLowerCase()) {
    return {
      ok: false,
      reason: "GenericPayment signer does not match authenticated builder",
    };
  }

  // AccessRecord echo (when present) — verify the server actually signed it
  // and the binding fields match the entry being served.
  if (payment.payload.accessRecord) {
    const ar = payment.payload.accessRecord;
    if (!input.entry) {
      return {
        ok: false,
        reason: "accessRecord supplied but no entry to bind it to",
      };
    }
    if (input.entry.dataPointId === null) {
      return {
        ok: false,
        reason: "accessRecord supplied but entry has no dataPointId yet",
      };
    }
    if (
      ar.dataPointId.toLowerCase() !== input.entry.dataPointId.toLowerCase()
    ) {
      return {
        ok: false,
        reason: "accessRecord.dataPointId does not match entry",
      };
    }
    if (ar.version !== String(input.entry.version)) {
      return { ok: false, reason: "accessRecord.version does not match entry" };
    }
    if (ar.accessor.toLowerCase() !== builder.toLowerCase()) {
      return {
        ok: false,
        reason: "accessRecord.accessor does not match authenticated builder",
      };
    }
    if (!input.serverOwner) {
      return {
        ok: false,
        reason: "serverOwner required to verify accessRecord signature",
      };
    }
    let recoveredServer: `0x${string}`;
    try {
      recoveredServer = await recoverTypedDataAddress({
        domain: dataRegistryDomain(input.gatewayConfig),
        types: RECORD_DATA_ACCESS_TYPES,
        primaryType: "RecordDataAccess",
        message: {
          ownerAddress: input.serverOwner,
          scope: input.entry.scope,
          version: BigInt(ar.version),
          accessor: ar.accessor,
          recordId: ar.recordId,
        },
        signature: ar.signature,
      });
    } catch {
      return { ok: false, reason: "accessRecord signature recovery failed" };
    }
    if (recoveredServer.toLowerCase() !== input.serverAddress.toLowerCase()) {
      return {
        ok: false,
        reason: "accessRecord signer is not this personal server",
      };
    }
  }

  return { ok: true, payment };
}
